# 1. O autorze klasyfikacji

__Imię: Sebastian  
Nazwisko: Derendarz  
Index: 228721  
Przedmiot: Analiza Danych, WEEIA, 5 semestr__

# 2. Opis Problemu

### a) Źródło danych

[UCI Machine Learning Repository - Mushroom Data Set](https://archive.ics.uci.edu/ml/datasets/Mushroom)  

Zestaw danych zawiera opisy hipotetycznych próbek odpowiadających 23 gatunkom prążkowanych grzybów z rodziny Agaricus i Lepiota. Każdy gatunek jest jadalny, trujący, lub o nieznanym stanie i niezalecany. Ta ostatnia klasa została połączona z trującą. Nie ma prostej zasady określania szlachetności grzyba; nie ma takiej reguły jak _"liście trzy, zdrowy ty"_ dla trującego dębu oraz bluszczu.

Dane zostały pobrane w formacie CSV oraz umieszczone w folderze roboczym użytkownika. Dostęp do pliku uzyskujemy poprzez wskazanie ścieżki `f'./{nazwa pliku}'`.  

Plik `20220124_agaricus_lepiota_data.csv` zawiera dane o grzybach. Jedynie pierwsze litery wartości atrybutów.  
Plik `20220124_agaricus_lepiota_data_expanded.csv` zawiera dane o grzybach. Pełne nazwy wartości atrybutów.  
Plik `20220124_agaricus_lepiota_names.csv` zawiera opis datasetu oraz atrybutów.  

Do klasyfikacji wykorzystamy plik `20220124_agaricus_lepiota_data_expanded.csv`.

### b) Potrzebne biblioteki

Poza wbudowanymi bibliotekami wykorzystywane są [pandas](http://pandas.pydata.org), [pandas-profiling](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/index.html), [numpy](https://numpy.org/), [scikit-learn](https://scikit-learn.org) i [Yellowbrick](http://www.scikit-yb.org).

- `pandas` zapewnia narzędzia, za pomocą których łatwo przekształca się dane.
- `pandas-profiling` służy do tworzenia i wizualizowania raportu z profilowania danych.
- `numpy` dostarcza szeroki zakres funkcji ułatwiających obliczenia numeryczne
- `scikit-learn` umożliwia tworzenie doskonałych modeli predykcyjnych.
- `yellowbrick` służy do wizualizowania wyników i weryfikowania skuteczności modelu.

### c) Jak załadować biblioteki?

Im prościej, tym lepiej. Użyjemy pip’a.  

`pip install nazwa_pakietu`

Jak łatwo się domyśleć – instaluje on nam wskazany pakiet.

Polecenie install pozwala nam, by wskazać konkretną wersję biblioteki, np:

- `pip install pandas` instaluje najnowszą wersję  
- `pip install pandas==1.4.0` instaluje konkretną wersję  
- `pip install 'pandas>=1.3.0'` instaluje wersję nowszą lub równą wskazanej  

Aby uniknąć niepotrzebnych komplikacji **preferujemy instalowanie konkretnych wersji**, proponowanych przez autora klasyfikacji. W przypadku problemów można dostosować wersję lub zainstalować wersję nowszą lub równą wskazanej.  

In [106]:
# '!{sys.executable} -m' is to allow to install python packages straight from jupyter notebook.
# It is equivalent to 'python -m'. Ehh miało być po polsku, rozpędziłem się :)
import sys

!{sys.executable} -m pip install pandas==1.4.0
!{sys.executable} -m pip install pandas_profiling==3.1.0
!{sys.executable} -m pip install numpy==1.19.5
!{sys.executable} -m pip install scikit-learn==1.0.2
!{sys.executable} -m pip install yellowbrick==1.3

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


### d) Wczytanie zbioru danych

In [107]:
import pandas as pd

header_list = [
    'edibility',
    'cap shape',
    'cap surface',
    'cap color',
    'bruises',
    'odor',
    'gill attachment',
    'gill spacing',
    'gill size',
    'gill color',
    'stalk shape',
    'stalk root',
    'stalk surface above ring',
    'stalk surface below ring',
    'stalk color above ring',
    'stalk color below ring',
    'veil type',
    'veil color',
    'ring number',
    'ring type',
    'spore print color',
    'population',
    'habitat'
]

df = pd.read_csv("./20220124_agaricus_lepiota_data_expanded.csv", names=header_list) #plik w katalogu użytkownika

# 3. Opis Danych

### a) Data sample - pierwsze 10 rekordów

In [108]:
df[:10]

edibility cap shape cap surface cap color  bruises    odor gill attachment  \
0    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
1    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
2    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
3    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
4    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
5    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES  ALMOND            FREE   
6    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES   ANISE            FREE   
7    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES   ANISE            FREE   
8    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES   ANISE            FREE   
9    EDIBLE    CONVEX      SMOOTH     WHITE  BRUISES   ANISE            FREE   

  gill spacing gill size gill color  ... stalk surface below ring  \
0      CROWDED    NARROW      WHITE  ...                   SMOOTH   
1      CROWDED    NARROW      WHITE  ...                   SMOOTH   
2      CROWDED    NARROW       PINK  ...                   SMOOTH   
3      CROWDED    NARROW       PINK  ...                   SMOOTH   
4      CROWDED    NARROW      BROWN  ...                   SMOOTH   
5      CROWDED    NARROW      BROWN  ...                   SMOOTH   
6      CROWDED    NARROW      WHITE  ...                   SMOOTH   
7      CROWDED    NARROW      WHITE  ...                   SMOOTH   
8      CROWDED    NARROW       PINK  ...                   SMOOTH   
9      CROWDED    NARROW       PINK  ...                   SMOOTH   

  stalk color above ring stalk color below ring veil type veil color  \
0                  WHITE                  WHITE   PARTIAL      WHITE   
1                  WHITE                  WHITE   PARTIAL      WHITE   
2                  WHITE                  WHITE   PARTIAL      WHITE   
3                  WHITE                  WHITE   PARTIAL      WHITE   
4                  WHITE                  WHITE   PARTIAL      WHITE   
5                  WHITE                  WHITE   PARTIAL      WHITE   
6                  WHITE                  WHITE   PARTIAL      WHITE   
7                  WHITE                  WHITE   PARTIAL      WHITE   
8                  WHITE                  WHITE   PARTIAL      WHITE   
9                  WHITE                  WHITE   PARTIAL      WHITE   

  ring number ring type spore print color population habitat  
0         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
1         ONE   PENDANT             BROWN    SEVERAL   WOODS  
2         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
3         ONE   PENDANT             BROWN    SEVERAL   WOODS  
4         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
5         ONE   PENDANT             BROWN    SEVERAL   WOODS  
6         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
7         ONE   PENDANT             BROWN    SEVERAL   WOODS  
8         ONE   PENDANT            PURPLE    SEVERAL   WOODS  
9         ONE   PENDANT             BROWN    SEVERAL   WOODS  

[10 rows x 23 columns]

### b) Data sample - ostatnie 10 rekordów

In [109]:
df[-10:]

edibility cap shape cap surface cap color bruises  odor gill attachment  \
8406    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8407    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8408    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8409    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8410    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8411    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8412    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8413    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8414    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   
8415    EDIBLE   KNOBBED      SMOOTH     BROWN      NO  NONE        ATTACHED   

     gill spacing gill size gill color  ... stalk surface below ring  \
8406        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8407        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8408        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8409        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8410        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8411        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8412        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8413        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8414        CLOSE     BROAD      BROWN  ...                   SMOOTH   
8415        CLOSE     BROAD      BROWN  ...                   SMOOTH   

     stalk color above ring stalk color below ring veil type veil color  \
8406                 ORANGE                 ORANGE   PARTIAL     ORANGE   
8407                 ORANGE                 ORANGE   PARTIAL     ORANGE   
8408                 ORANGE                 ORANGE   PARTIAL      BROWN   
8409                 ORANGE                 ORANGE   PARTIAL      BROWN   
8410                 ORANGE                 ORANGE   PARTIAL      BROWN   
8411                 ORANGE                 ORANGE   PARTIAL      BROWN   
8412                 ORANGE                 ORANGE   PARTIAL      BROWN   
8413                 ORANGE                 ORANGE   PARTIAL      BROWN   
8414                 ORANGE                 ORANGE   PARTIAL      BROWN   
8415                 ORANGE                 ORANGE   PARTIAL      BROWN   

     ring number ring type spore print color population habitat  
8406         ONE   PENDANT              BUFF    SEVERAL  LEAVES  
8407         ONE   PENDANT              BUFF  CLUSTERED  LEAVES  
8408         ONE   PENDANT            YELLOW    SEVERAL  LEAVES  
8409         ONE   PENDANT            YELLOW  CLUSTERED  LEAVES  
8410         ONE   PENDANT             BROWN    SEVERAL  LEAVES  
8411         ONE   PENDANT             BROWN  CLUSTERED  LEAVES  
8412         ONE   PENDANT            ORANGE    SEVERAL  LEAVES  
8413         ONE   PENDANT            ORANGE  CLUSTERED  LEAVES  
8414         ONE   PENDANT              BUFF    SEVERAL  LEAVES  
8415         ONE   PENDANT              BUFF  CLUSTERED  LEAVES  

[10 rows x 23 columns]

### c) Przykłady metod z biblioteki pandas opisujących dane

- Suma wartości not Null dla każdego atrybutu.

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8416 entries, 0 to 8415
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   edibility                 8416 non-null   object
 1   cap shape                 8416 non-null   object
 2   cap surface               8416 non-null   object
 3   cap color                 8416 non-null   object
 4   bruises                   8416 non-null   object
 5   odor                      8416 non-null   object
 6   gill attachment           8416 non-null   object
 7   gill spacing              8416 non-null   object
 8   gill size                 8416 non-null   object
 9   gill color                8416 non-null   object
 10  stalk shape               8416 non-null   object
 11  stalk root                5936 non-null   object
 12  stalk surface above ring  8416 non-null   object
 13  stalk surface below ring  8416 non-null   object
 14  stalk color above ring  

- Suma wartości Null dla każdego atrybutu.

In [111]:
df.isnull().sum()

edibility                      0
cap shape                      0
cap surface                    0
cap color                      0
bruises                        0
odor                           0
gill attachment                0
gill spacing                   0
gill size                      0
gill color                     0
stalk shape                    0
stalk root                  2480
stalk surface above ring       0
stalk surface below ring       0
stalk color above ring         0
stalk color below ring         0
veil type                      0
veil color                     0
ring number                    0
ring type                      0
spore print color              0
population                     0
habitat                        0
dtype: int64

- lista wszystkich dostępnych metod dla obiektu DataFrame z bilblioteki pandas jest dostępna [tutaj](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

### d) Raport z profilowania danych z wykorzystaniem pandas profiling

Doskonałe narzędzie, aby niskim nakładem pracy podsumować oraz wstępnie przeanalizować opracowywane dane. Znakomicie zastępuje i jednocześnie wizualizuje rezultaty wywołania metod z punktu **c** powyżej.

In [112]:
import pandas_profiling

pandas_profiling.ProfileReport(df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# 4. Przetwarzanie Danych

### a) Konwersja oznaczenia brakujących wartości

W kolumnie `stalk root` występują braki danych. W datasecie pobranym z UCI pola te były oznaczone znakiem zapytania "?". Na potrzeby analizy zamieniłem znaki zapytania na wartość "NaN". Dzięki temu możliwe jest bezpośrednie znalezienie brakujących wartości w datasecie. W przypadku znaków zapytania potrzebne byłyby dodatkowe operacje na danych. Uznałem, że zamiana "?" na "NaN" jest dobrym rozwiązaniem, ponieważ klasyfikacja jest przygotowana tylko dla tych danych, a dane oraz ich format nie ulegną zmianie. Mówiąc wprost, było szybciej.

### b) Czyszczenie danych

Analiza raportu profilowania wykazała, że atrybut `veil type` ma taką samą wartość, `PARTIAL`, dla każdego rekordu w datasecie. Informacja ta jest więc zbędna. Postanowiłem ją usunąć.  

In [113]:
del df['veil type']

### c) Uzupełniene brakujących danych

Artybut `stalk root`, jedyny, który ma brakujące 2480 (29.5%) wartości, nie będzie brany pod uwagę w bazowej klasyfikacji uzwględniającej jedynie atrybuty wysoko skorelowane z wynikiem. Dzięki temu nie ma potrzeby uzupełniania brakujących danych.

### d) Wybór cech oraz przekształcenia danych

Zdecydowałem się na dokonanie trzech klasyfikacji:
- z wykorzystaniem jednego atrybutu z tych, które w raporcie z profilowania danych zostały wskazane jako wysoko skorelowane z kolumną wynikową. DataFrame zostanie nazwany `df2`.
- z wykorzystaniem wszystkich atrybutów, które w raporcie z profilowania danych zostały wskazane jako wysoko skorelowane z kolumną wynikową. DataFrame zostanie nazwany `df3`.
- z wykorzystaniem wszystkich atrybutów. DataFrame zostanie nazwany `df4`.  

Wartości tekstowe w powstałych DataFrame-ach zostaną skonwertowane do wartości liczbowych przy wykorzystaniu funkcji `get_dummies` z biblioteki `pandas`. Bazowy DataFrame - `df` nie ulegnie zmianie.

In [137]:
def keep_cols(dataframe, keep_these):
    """Keep only the columns [keep_these] in a DataFrame, delete
    all other columns. 
    """
    drop_these = list(set(list(dataframe)) - set(keep_these))
    return dataframe.drop(drop_these, axis = 1)

df2 = df.pipe(keep_cols, ['edibility', 'odor']).pipe(pd.get_dummies, drop_first=True)

df3 = df.drop(
        columns=[
            'cap shape',
            'cap surface',
            'cap color',
            'gill attachment',
            'stalk shape',
            'veil color',
            'ring number',
            'ring type',
            'habitat'
        ]
    ).pipe(pd.get_dummies, drop_first=True)

df4 = pd.get_dummies(df, drop_first=True)

# 5. Tworzenie modelu oraz ocena trafności predykcji

### a) Funkcja służąca do predykcji jadalności grzyba

Kompaktowa, implementująca algorytm _k-nearest neighbos_ (k najbliższych sąsiadów). Zostanie wykorzystana do analizy datasetu niezależnie od cech, które wybraliśmy. Proszę zapoznać się z docstringiem oraz kodem w celu zrozumienia sposobu działania oraz wykorzystania funkcji. Wartości zwrócone przez funckję mogą być w prosty sposób ocenione poprzez wywołanie funkcji `accuracy_score(yk_test, yk_pred)` z biblioteki `sklearn.metrics`. Wynik wywołania tej funkcji będę uznawał za ostateczny wyznacznik jakości klasyfikacji.

In [158]:
from typing import Tuple

import numpy as np
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

def predict_edibility(dataframe: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
    '''Predict mushroom edibility.
    
    One condition that must be met is that desired result of classification
    must be stored in the first column of DataFrame in a column named 'edibility_POISONOUS'.
    
    params:
        dataframe: pandas DataFrame object to be analized
    returns:
        Tuple of test and predicted values for dataframe
        than can be used to assess accuracy of prediction.
    '''
    X = dataframe.iloc[:, 1:]
    y = dataframe['edibility_POISONOUS']
    yk = y.values

    # division into test and teach sets of values
    idx_ucz, idx_test = train_test_split(np.arange(X.shape[0]),test_size=0.9, random_state=12345)

    X_ucz, X_test = X.iloc[idx_ucz, :], X.iloc[idx_test, :]
    y_ucz, y_test = y[idx_ucz], y[idx_test]
    yk_ucz, yk_test = yk[idx_ucz], yk[idx_test]
    X_ucz.shape, X_test.shape, y_ucz.shape, y_test.shape

    knn = neighbors.KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_ucz, yk_ucz)
    yk_pred = knn.predict(X_test)
    return yk_test, yk_pred

### b) Ocena trafności predykcji modelu wykorzytującego jedynie jeden z najwyżej skorelowanych atrybutów

In [159]:
yk_test, yk_pred = predict_edibility(df2)
accuracy = accuracy_score(yk_test, yk_pred)


print(f'Accuracy of prediction: {accuracy*100:.2f}%')

Accuracy of prediction: 98.23%


### c) Ocena trafności predykcji modelu wykorzytującego jedynie najwyżej skorelowane atrybuty

In [160]:
yk_test, yk_pred = predict_edibility(df3)
accuracy = accuracy_score(yk_test, yk_pred)


print(f'Accuracy of prediction: {accuracy*100:.2f}%')

Accuracy of prediction: 99.05%


### d) Ocena trafności predykcji modelu wykorzytującego wszystkie atrybuty

In [161]:
yk_test, yk_pred = predict_edibility(df4)
accuracy = accuracy_score(yk_test, yk_pred)

print(f'Accuracy of prediction: {accuracy*100:.2f}%')

Accuracy of prediction: 99.38%


# 6. Podsumownie

Dzięki wtępnej ocenie uzyskanej przy wykorzystaniu raportu z profilowania danych byłem w stanie ocenić, które atrybuty są wysoko skorelowane z kolumną wynikową. Klasyfikacja z wykorzystaniem tylko jednego z takich atrybutów - `odor` dała bardzo satysfakcjonujące wyniki - __trafność 98.23%__.  

Klasyfikacja z wykorzystaniem wszystkich atrybutów wskazanych jako wysoko skorelowane __podniosła poziom trafności do 99.05%__  

Klasyfikując dane z uwzględnieniem wszystkich atrybutów byłem w stanie uzyskać __trafność na poziomie 99.38%.__  

Powyższe klasyfikacje wykonałem dzieląc bazowy dataset na część uczącą oraz testową w proporcjach __10%__ oraz __90%__ accordingly.  

Dzieląc bazowy dataset na część uczącą oraz testową w proporcjach __80%__ oraz __20%__ accordingly uzyskałem wyniki na poziomie __98.69%, 100.00% oraz 100.00%__. Można przyjąć, że dla opracowywanego datasetu wziększenie części uczącej w stosunku do części testowej jest jednym z sposobów na podniesienie trafności klasyfikacji. Nie umieściłem obliczeń dla tych proporcji, ponieważ nie chciałem, aby klasyfikacja starciła charakter edukacyjny. Mówiąc wprost, gdy wychodzi prawie 100.00% trafności za każdym razem zabawa traci sens :)

__Final words:__ Uważam, że powyższą klasyfikację można uznać za zakończoną sukcesem.